# Generated by Django 3.1.7 on 2021-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obgy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='empty', max_length=10)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodpressure',
            name='value',
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='dbp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bloodpressure',
            name='sbp',
            field=models.FloatField(default=0),
        ),
    ]
